#!/usr/bin/env python3
import argparse
import os
import sys
from datetime import datetime, timedelta, timezone

import yfinance as yf
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

from portfolio_tracker import load_transactions_from_sheet, fifo_match


def get_open_tickers():
    transactions = load_transactions_from_sheet()
    open_positions, _ = fifo_match(transactions)
    tickers = sorted({t for _, t in open_positions})
    return tickers


def fetch_news(ticker, max_days=7):
    try:
        t = yf.Ticker(ticker)
        raw = t.get_news() or []
    except Exception:
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(days=max_days)
    filtered = []
    for item in raw:
        content = item.get("content", {})
        pub_date = content.get("pubDate", "")
        try:
            pub_time = datetime.fromisoformat(pub_date.replace("Z", "+00:00"))
        except (ValueError, AttributeError):
            continue
        if pub_time < cutoff:
            continue
        filtered.append({
            "title": content.get("title", ""),
            "publisher": content.get("provider", {}).get("displayName", ""),
            "link": content.get("canonicalUrl", {}).get("url", ""),
            "summary": content.get("summary", ""),
            "time": pub_time,
        })
    return filtered


def summarize_ticker(ticker, items, api_key):
    from openai import OpenAI

    client = OpenAI(api_key=api_key, base_url="https://opencode.ai/zen/go/v1")

    lines = []
    for item in items:
        lines.append(f"  - {item['title']} ({item['publisher']})")
        if item["summary"]:
            lines.append(f"    {item['summary'][:200]}")

    news_text = "\n".join(lines)
    prompt = f"""You are a financial news analyst. Below is recent news (past week) for {ticker}.

{news_text}

Summarize the key developments in 1-2 concise paragraphs. Focus on material events, earnings, product launches, regulatory changes, and sector trends. Omit routine price commentary."""

    response = client.chat.completions.create(
        model="deepseek-v4-flash",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content


def send_news_email(per_ticker_summaries, news_by_ticker, smtp_config, recipients):
    import smtplib
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart

    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    ticker_blocks = []
    for ticker in sorted(news_by_ticker):
        items = news_by_ticker[ticker]
        summary = per_ticker_summaries.get(ticker, "")
        articles = ""
        if items:
            articles = "".join(
                f'<li><a href="{item["link"]}">{item["title"]}</a> &mdash; {item["publisher"]}</li>'
                for item in items
            )
            articles = f"<ul>{articles}</ul>"

        ticker_blocks.append(f"""<h3>{ticker}</h3>
<p><b>AI Summary</b></p>
<p>{summary}</p>
<p><b>Articles</b></p>
{articles}
<hr>""")

    body_html = "\n".join(ticker_blocks)

    html = f"""<html>
<body style="font-family: Arial, sans-serif;">
    <h2>Watchlist News Summary</h2>
    <p>Date: {date_str}</p>
    {body_html}
    <p style="color: #888; font-size: 12px; margin-top: 20px;">
        Generated by Watchlist News Summarizer &mdash; not financial advice.
    </p>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Watchlist News Summary - {date_str}"
    msg["From"] = smtp_config["user"]
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(smtp_config["user"], smtp_config["password"])
        server.sendmail(smtp_config["user"], recipients, msg.as_string())


def parse_recipients(raw):
    recipients = []
    for part in raw.split(","):
        part = part.split("#")[0].strip()
        if part:
            recipients.append(part)
    return recipients


def main():
    parser = argparse.ArgumentParser(description="Watchlist news summarizer")
    parser.add_argument("--no-email", action="store_true", help="Print to console only")
    args = parser.parse_args()

    tickers = get_open_tickers()
    if not tickers:
        print("No open positions found.")
        sys.exit(1)

    print(f"Watchlist ({len(tickers)} open positions): {', '.join(tickers)}")
    print("Fetching news...")

    news_by_ticker = {}
    for ticker in tickers:
        items = fetch_news(ticker)
        news_by_ticker[ticker] = items
        print(f"  {ticker}: {len(items)} articles")

    total = sum(len(v) for v in news_by_ticker.values())
    if total == 0:
        print("No news found. Nothing to summarize.")
        return

    api_key = os.getenv("OPENCODE_GO_API_KEY")
    if not api_key:
        print("OPENCODE_GO_API_KEY not set in .env")
        sys.exit(1)

    print("Summarizing with DeepSeek V4 Flash...")
    per_ticker_summaries = {}
    for ticker, items in news_by_ticker.items():
        if not items:
            continue
        summary = summarize_ticker(ticker, items, api_key)
        per_ticker_summaries[ticker] = summary
        print(f"  {ticker}: summarized")
        print(f"    {summary[:120]}...")

    if not per_ticker_summaries:
        print("No tickers with news to summarize.")
        return

    if not args.no_email:
        smtp_user = os.getenv("SMTP_USER")
        smtp_pass = os.getenv("SMTP_PASSWORD")
        raw_rcpt = os.getenv("REPORT_RECIPIENTS", "")

        if smtp_user and smtp_pass and raw_rcpt:
            recipients = parse_recipients(raw_rcpt)
            if recipients:
                print(f"Sending email to {len(recipients)} recipient(s)...")
                send_news_email(per_ticker_summaries, news_by_ticker, {"user": smtp_user, "password": smtp_pass}, recipients)
                print("Email sent!")
            else:
                print("No valid recipients.")
        else:
            print("SMTP not configured.")


if __name__ == "__main__":
    main()
