import smtplib
import csv
import io
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


def build_html_table(df, indices):
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    index_str = ", ".join([i.upper() for i in indices])

    rows_html = ""
    for _, row in df.iterrows():
        ticker = row["Ticker"]
        price = row["Price"]
        vs_50 = row.get("vs_50_SMA%", "")
        atr = row.get("ATR%", "")
        vcp_status = row.get("VCP_Status", "")
        vcp_score = row.get("VCP_Score", "")
        pb_status = row.get("Pullback_Status", "")
        pb_score = row.get("Pullback_Score", "")
        ad = row.get("AD", "")
        eps = row.get("EPS_Rating", "")
        ind_rank = row.get("Ind_Rank", "")
        earnings = row.get("Next_Earnings", "")
        rs = row.get("RS_Rating", "")
        rs_trend = row.get("RS_Trend", "")
        rs_div = row.get("RS_Div", "")
        corr_div = row.get("Corr_Div", "")
        brk_order = row.get("Brk_Order", "")
        exh_score = row.get("Exh_Score", "")
        exh_status = row.get("Exh_Status", "")
        dist_score = row.get("Dist_Score", "")
        dist_status = row.get("Dist_Status", "")
        viol_status = row.get("Viol", "")
        viol_score = row.get("V_Sc", "")

        rows_html += f"""<tr>
            <td><a href="https://www.tradingview.com/chart/?symbol={ticker}">{ticker}</a></td>
            <td>{price}</td>
            <td>{vs_50}%</td>
            <td>{atr}%</td>
            <td>{vcp_status}</td>
            <td>{vcp_score}</td>
            <td>{pb_status}</td>
            <td>{pb_score}</td>
            <td>{ad}</td>
            <td>{eps}</td>
            <td>{ind_rank}</td>
            <td>{earnings}</td>
            <td>{rs}</td>
            <td>{rs_trend}</td>
            <td>{rs_div}</td>
            <td>{corr_div}</td>
            <td>{brk_order}</td>
            <td>{exh_status}</td>
            <td>{exh_score}</td>
            <td>{dist_status}</td>
            <td>{dist_score}</td>
            <td>{viol_status}</td>
            <td>{viol_score}</td>
        </tr>"""

    html = f"""<html>
    <body style="font-family: Arial, sans-serif;">
        <h2>SEPA Stage 2 Screener Results</h2>
        <p>Date: {date_str} | Universe: {index_str} | Passing: {len(df)} stocks</p>
        <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse; font-size: 14px;">
            <tr style="background: #2c3e50; color: white;">
                <th>Ticker</th><th>Price</th><th>vs 50 SMA%</th><th>ATR(22)%</th>
                <th>VCP</th><th>Score</th><th>Pullback</th><th>PB Sc</th><th>A/D</th><th>EPS</th><th>Ind Rk</th><th>Next Earnings</th><th>RS</th>
                <th>RS Trend</th><th>RS Div</th><th>Corr Div</th><th>Brk Order</th>
                <th>Exh</th><th>Exh Sc</th><th>Dist</th><th>Dist Sc</th>
                <th>Viol</th><th>V Sc</th>
            </tr>
            {rows_html}
        </table>
        <p style="color: #888; font-size: 12px; margin-top: 20px;">
            Generated by SEPA Stage 2 Screener &mdash; not financial advice.
        </p>
    </body>
    </html>"""
    return html


def _build_csv(df):
    out = io.StringIO()
    writer = csv.writer(out)
    cols = df.columns.tolist() + ["Link"]
    writer.writerow(cols)
    for _, row in df.iterrows():
        vals = row.tolist() + [f"https://www.tradingview.com/chart/?symbol={row['Ticker']}"]
        writer.writerow(vals)
    return out.getvalue()


def send_email(df, indices, smtp_config, recipients):
    date_str = datetime.now().strftime("%Y-%m-%d")
    html = build_html_table(df, indices)
    csv_data = _build_csv(df)

    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"SEPA Screener Results - {date_str}"
    msg["From"] = smtp_config["user"]
    msg["To"] = ", ".join(recipients)

    body = MIMEMultipart("alternative")
    body.attach(MIMEText(html, "html"))
    msg.attach(body)

    csv_part = MIMEBase("text", "csv")
    csv_part.set_payload(csv_data)
    encoders.encode_base64(csv_part)
    csv_part.add_header("Content-Disposition", "attachment", filename=f"sepa_results_{date_str}.csv")
    msg.attach(csv_part)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(smtp_config["user"], smtp_config["password"])
        server.sendmail(smtp_config["user"], recipients, msg.as_string())
