import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def build_html_table(df, indices):
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    index_str = ", ".join([i.upper() for i in indices])

    rows_html = ""
    for _, row in df.iterrows():
        ticker = row["Ticker"]
        price = row["Price"]
        vs_50 = row.get("vs_50_SMA%", "")
        sma50 = row.get("SMA50", "")
        sma150 = row.get("SMA150", "")
        sma200 = row.get("SMA200", "")
        atr = row.get("ATR_22", "")
        vcp_status = row.get("VCP_Status", "")
        vcp_score = row.get("VCP_Score", "")
        earnings = row.get("Next_Earnings", "")
        rs = row.get("RS_Rating", "")

        rows_html += f"""<tr>
            <td><a href="https://www.tradingview.com/chart/?symbol={ticker}">{ticker}</a></td>
            <td>{price}</td>
            <td>{vs_50}%</td>
            <td>{sma50}</td>
            <td>{sma150}</td>
            <td>{sma200}</td>
            <td>{atr}</td>
            <td>{vcp_status}</td>
            <td>{vcp_score}</td>
            <td>{earnings}</td>
            <td>{rs}</td>
        </tr>"""

    html = f"""<html>
    <body style="font-family: Arial, sans-serif;">
        <h2>SEPA Stage 2 Screener Results</h2>
        <p>Date: {date_str} | Universe: {index_str} | Passing: {len(df)} stocks</p>
        <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse; font-size: 14px;">
            <tr style="background: #2c3e50; color: white;">
                <th>Ticker</th><th>Price</th><th>vs 50 SMA%</th><th>SMA50</th><th>SMA150</th><th>SMA200</th><th>ATR(22)</th>
                <th>VCP</th><th>VCP Score</th><th>Next Earnings</th><th>RS Rating</th>
            </tr>
            {rows_html}
        </table>
        <p style="color: #888; font-size: 12px; margin-top: 20px;">
            Generated by SEPA Stage 2 Screener &mdash; not financial advice.
        </p>
    </body>
    </html>"""
    return html


def send_email(df, indices, smtp_config, recipients):
    html = build_html_table(df, indices)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"SEPA Screener Results - {datetime.now().strftime('%Y-%m-%d')}"
    msg["From"] = smtp_config["user"]
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(smtp_config["user"], smtp_config["password"])
        server.sendmail(smtp_config["user"], recipients, msg.as_string())
